# Generated by Django 5.2.4 on 2025-07-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('is_common', models.BooleanField(default=True)),
                ('word_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palavra do Dicionário',
                'verbose_name_plural': 'Palavras do Dicionário',
            },
        ),
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('neologism_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise de Texto',
                'verbose_name_plural': 'Análises de Texto',
            },
        ),
        migrations.CreateModel(
            name='DetectedNeologism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('word_class', models.CharField(choices=[('substantivo', 'Substantivo'), ('adjetivo', 'Adjetivo'), ('verbo', 'Verbo'), ('advérbio', 'Advérbio'), ('outros', 'Outros')], max_length=20)),
                ('formation_type', models.CharField(choices=[('derivação_prefixal', 'Derivação Prefixal'), ('derivação_sufixal', 'Derivação Sufixal'), ('composição', 'Composição'), ('estrangeirismo', 'Estrangeirismo'), ('outros', 'Outros')], max_length=30)),
                ('sentence_context', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neologism_app.textanalysis')),
            ],
            options={
                'verbose_name': 'Neologismo Detectado',
                'verbose_name_plural': 'Neologismos Detectados',
            },
        ),
        migrations.CreateModel(
            name='UserDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('is_neologism', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Palavra Personalizada',
                'verbose_name_plural': 'Palavras Personalizadas',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
